config/routes.rb
Rails.application.routes.draw do


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
   devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }


  root 'products#home'


  resources :products
  post "/products/new", to: "products#new"

  resources :line_products, only: [:new, :create, :show, :index]

  resources :carts
  get 'carts/:id/checkout', to: 'carts#checkout'
  post 'carts/:id/checkout', to: 'carts#checkout', as: 'checkout'

  get 'users/:id/thank_you', to: 'users#thank_you'
  post 'users/:id/thank_you', to: 'users#thank_you', as: 'thank_you'


  resources :users do
    resources :products
    resources :addresses
    resources :messages
  end



end

app/models/cart.rb
class Cart < ApplicationRecord

  belongs_to :user

  has_many :line_products
  has_many :products, through: :line_products

  def total
    total = 0
    self.line_products.each do |line_product|
      total += line_product.product.price * line_product.quantity
    end
    total
  end

  def add_product(line_params)
    current_product = line_products.find_by(product_id: line_params[:product_id])
      if current_product
        current_product.quantity += line_params[:quantity].to_i #you have to somehow get your error messages to play a role here.
        current_product.save
      else
        current_product = line_products.new
        current_product.quantity = line_params[:quantity]
        current_product.product_id = line_params[:product_id]
        current_product.save
      end
      current_product
   end

   def checkout
    self.status = "submitted"
   end


end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :set_cart, only: [:checkout, :destroy, :show]

  def show  
    respond_to do |format|
      format.html { render :show }
      format.json { render json: @cart.line_products}
    end



    # respond_to do |format|
    #   format.html { render :show, layout: false }
      # this code was right beside render :show `, layout: false`. Copy and paste this in this function if there is any problems.

  end

  def checkout
    @cart.checkout
    redirect_to new_user_address_path(current_user) if @cart.valid?
  end

  def destroy
    @product = @cart.products
      if @product
        @product.delete_all
      end
    redirect_to root_path
  end

  private

  def cart_params
    params.require(:cart).permit(:user_id)
  end

  def set_cart
    @cart = current_user.current_cart
  end


end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/_cart.html.erb
    <table class="cart_table">
  <thead>
    <tr>
      <th>Product</th>
      <th>Name</th>
      <th>Quantity</th>
      <th>Price</th>
      <th></th>
    </tr>
  </thead>
  <tbody>

      <tr>
        <% cart.line_products.each do |line_product| %>
          <% if line_product.product.date_delivered == Date.today %>
        <td><%= image_tag("flowers/#{rand(9)}.jpg") %></td>
        <td><%= line_product.product.name %></td>
        <td><%= line_product.quantity%></td>
        <td><%= number_to_currency(line_product.product.price.to_f) %></td>
        <td><%= link_to "<span class='material-icons' style='font-size:32px;'>delete_outline</span>".html_safe, cart_path(cart), method: :delete, :data => {:confirm => 'This will empty everything in your cart. Are you sure?'}%></td>
        <% end %>
        <% end %>
     </tr>
  </tbody>
</table>


<table class="grand_total">
  <thead>
    <tr>
      <th><strong>Grand Total:</strong></th>
      <th><%= number_to_currency(cart.total.to_f) %></th>
    </tr>
  </thead>
</table>

app/views/carts/show.html.erb
<body class=center>
  <div class="cart">


      <h1 class="cart_heading">Your Cart</h1>
       <%= render partial: "cart", locals: {cart: @cart} %>

      <% if @cart.total != 0 %>
        <div class="bigbutton"> <%= button_to 'Proceed to Checkout', checkout_path, method: :post %> </div>
      <% end %>

    </div>
</body>