config/routes.rb
Rails.application.routes.draw do


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
   devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }


  root 'products#home'


  resources :products
  post "/products/new", to: "products#new"

  resources :line_products, only: [:new, :create, :show, :index]

  resources :carts
  get 'carts/:id/checkout', to: 'carts#checkout'
  post 'carts/:id/checkout', to: 'carts#checkout', as: 'checkout'

  get 'users/:id/thank_you', to: 'users#thank_you'
  post 'users/:id/thank_you', to: 'users#thank_you', as: 'thank_you'


  resources :users do
    resources :products
    resources :addresses
    resources :messages
  end



end

app/controllers/addresses_controller.rb
class AddressesController < ApplicationController
  helper_method :user


  def index
    # @shipping_add = user.addresses.find_by(address_type: "Shipping")
    # @billing_add = user.addresses.find_by(address_type: "Billing")
    # @message = user.messages.last
    # response = { :shipping_address => @shipping_address, :billing_address => @billing_address, :message => @message }
    # respond_to do |format|
    #   format.html { render :index }
    #   format.json  { render :json => response }
    # end
  end

  def new
    user.addresses.build(address_type: "Shipping")
    user.addresses.build(address_type: "Billing")
    user.messages.build
  end


  def create
    if user.update(address_params)
      #  flash[:notice] = "Your Order Was Successful"

       @shipping_add = user.addresses[-2]
       @billing_add = user.addresses[-1]
       @message = user.messages.last

       render 'addresses/index'

      else
        render :json => { :errors => user.errors.full_messages }, :status => 442
          flash[:error] = "Sorry. Your Order Did Not Go Through. Please key in your address again."
    end
  end


    private

    def address_params
      params.require(:user).permit(:email, :addresses_attributes => [:street_1, :street_2, :city, :state, :zip_code, :address_type], :messages_attributes => [:content])
    end

    def user
      current_user
    end


end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/views/addresses/_form_errors.html.erb
    <% if form.object.errors.any? %>
      <div class="field_with_errors">
        <h3>
          <%= pluralize(form.object.errors.count, "error") %>
          prevented your order from being processed:
        </h3>
        <ul>
        <% form.object.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
<br>

app/views/addresses/index.html.erb
<body class=center>

<h1 class="review_heading"> Order Review </h1>

  <table class="review_order_table">

    <thead>
      <tr>

        <th><%= @shipping_add.address_type %></th>

        <th><%= @billing_add.address_type %></th>
        <th> Your Message</th>


      </tr>
    </thead>
    <tbody>

        <tr>

          <td>
            <%= @shipping_add.street_1.titleize %>
            <%= @shipping_add.street_2.titleize %>
            <%= @shipping_add.city.titleize %>
            <%= @shipping_add.state.titleize %>
            <%= @shipping_add.zip_code %>
          </td>

          <td>
            <%= @billing_add.street_1.titleize %>
            <%= @billing_add.street_2.titleize %>
            <%= @billing_add.city.titleize %>
            <%= @billing_add.state.titleize %>
            <%= @billing_add.zip_code %>
          </td>
          <td>
            <%= @message.content.titleize %>
            <% if @message.content.empty? %>
             no messages
            <% end %>
          </td>
     </tr>

    </tbody>
  </table>

  <%= render partial: "carts/cart", locals: {cart: user.current_cart}  %>

   <span class="place_order_button"><%= button_to 'Place my Order', thank_you_path(current_user), data: { confirm: 'Confirm?' } %></span>


</body>

app/views/addresses/new.html.erb
<body class=center>

    <%= form_for user, :url => user_addresses_path(user), method: :post do |f| %>
      <h1 class="address_heading"> Delivery Address </h1>

      <%= f.fields_for :addresses do |address| %>
      <% $add = address.object %>
        <% if !address.object.id.present? %>
          <%= address.hidden_field :address_type %>


          <%= render partial: "form_errors", locals: {form: address} %>


          <label><strong><%= address.object.address_type %></strong></label>
          <fieldset>

            <p><%= address.label :street_1 %>* </p>
            <p class="input_street_1"><%= address.text_field :street_1 %> </p>


            <p><%= address.label :street_2 %></p>
            <p class="input_street_2"><%= address.text_field :street_2 %></p>

          </br>

            <span class="city">
              <%= address.label :city %>*
              <%= address.text_field :city %>
            </span>

            <span class="state">
              <%= address.label :state %>*
              <%= address.text_field :state %>
            </span>

            <span class="zip_code">
              <%= address.label :zip_code %>*
              <%= address.text_field :zip_code %>
            </span>
          </fieldset>
        <% end %>
      <% end %>
      <br></br>

      <%= f.fields_for :messages do |message| %>

        <% if !message.object.id.present? %>
          <label><strong>Message to Recipient</strong></label>

          <fieldset>


        <%= render partial: "form_errors", locals: {form: message} %>

            <p><%= message.label :content %></p>
            <p class="content"><%= message.text_area :content, placeholder: "Write a little note to your loved one...."%></p>


          </fieldset>
        <% end %>
      <% end %>
        <br></br>
        * required fields
        <br></br>
        <br>
        <br>

    <div id="review_order_button">  <%= f.submit "Review my Order" %> </div>
    <% end %>

    <div id="address_form">
    <div id="address_error_msg">

</div>

</body>